# stage 1

FROM node:14-alpine AS my-app-build
WORKDIR /app
COPY . .
RUN npm ci && npm run build

# stage 2

FROM nginx:1.19.4-alpine
COPY --from=my-app-build /app/dist/client /usr/share/nginx/html
EXPOSE 80
