# stage 1

FROM node:14-alpine AS my-app-build
WORKDIR /usr/share
RUN mkdir ng
WORKDIR ng
COPY . .
RUN npm install
RUN npm ci && npm run build

# stage 2

FROM nginx:1.19.4-alpine
COPY --from=my-app-build /usr/share/ng /usr/share/nginx/html
EXPOSE 80
